cc_library(
    name = "fup_facade_lib",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//facade/helper:fup_facade_helper_lib",
        "//facade/manager:fup_facade_manager_lib",
        "//core:fup_core_lib"
    ]
)