#pragma once

#ifndef FUP_CORE_INTERFACE_CONSTANTS_HPP
#define FUP_CORE_INTERFACE_CONSTANTS_HPP
#define GENERAL_BUFFER_SIZE 1024
#define METADATA_FIXED_BUFFER_SIZE 10
#define PACKET_FIXED_BUFFER_SIZE 40
#define RESPONSE_FIXED_BUFFER_SIZE 12
#define REQUEST_FIXED_BUFFER_SIZE 9
#endif