#pragma once

#ifndef FUP_CORE_HELPER_CONSTANTS_HPP
#define FUP_CORE_HELPER_CONSTANTS_HPP
#define METADATA_FIXED_BUFFER_SIZE 10
#define RESEND_BUFFER_SIZE 64
#define KEY_BUFFER_SIZE 64
#define PACKAGE_FIXED_BUFFER_SIZE 40
#define RESPONSE_BUFFER_SIZE 8
#endif