#pragma once

#ifndef FUP_CORE_HELPER_CONSTANTS_HPP
#define FUP_CORE_HELPER_CONSTANTS_HPP
#define METADATA_BUFFER_SIZE 10
#define RESEND_BUFFER_SIZE 18
#define KEY_BUFFER_SIZE 64
#define PACKET_FIXED_BUFFER_SIZE 40
#endif