cc_library(
    name = "fup_facade_helper_lib",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//core:fup_core_lib"
    ],
    visibility = ["//facade:__pkg__","//facade/manager:__pkg__"]
)